# docker-compose.yml
version: "3"
services:
  subsocial-ui:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: dappforce/subsocial-ui:latest
    container_name: subsocial-web-ui
    network_mode: "host"
    restart: on-failure

  nginx:
    build: ./nginx
    container_name: subsocial-nginx-proxy
    image: dappforce/subsocial-proxy:latest
    network_mode: "host"
